### ISSUE TITLE
Criação de YAML de configuração

### ISSUE THREAD

**Issue by fnunezzz** [fnunezzz/antaeus#9]
- Utilizar YAML para configuração das validações

formato de exemplo:

```yml
resource_rules:
    issues:
        rules:
            - name: Guideline de abertura
              conditions:
                  state: opened
                  description:
                      length: 25
              comment: |
                  :wave: {{author}}, adicione pelo menos uma label {{labels}}. Essas labels nos ajudam a manter nossos projetos organizados e categorizados corretamente para atuação.

                  Se você tiver dúvida de quais labels colocar fale com seu líder técnico, ele com certeza lhe ajudará!

                  *Essa mensagem foi gerada automaticamente*
            - name: Guideline de inatividade
              conditions:
                  date:
                      attribute: updated_at
                      condition: older_than
                      interval_type: weeks
                      interval: 3
                  state: opened
              labels:
                  remove: state
              comment: |
                  :wave: {{author}} essa issue está parada a mais de {{delta}} {{delta_type}}.

                  Label de `state` alterada para ~"state::pendente-analise"

                  /label ~"state::pendente-analise"

                  *Essa mensagem foi gerada automaticamente*

```
